"""add_is_featured

Revision ID: 01d5189d3343
Revises: ccd520744443
Create Date: 2026-04-07 01:40:39.029167

"""
from alembic import op
import sqlalchemy as sa


revision = '01d5189d3343'
down_revision = 'ccd520744443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
