"""add variant_mode to categories

Revision ID: 9584302d58e5
Revises: 362967cb20ab
Create Date: 2026-04-03 17:04:55.265184

"""
from alembic import op
import sqlalchemy as sa


revision = '9584302d58e5'
down_revision = '362967cb20ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('variant_mode', sa.String(), server_default='multi_qty', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'variant_mode')
    # ### end Alembic commands ###
