"""add cashfree payment fields to orders

Revision ID: a9edbaef5a0d
Revises: d14be4f4cf36
Create Date: 2026-04-03 05:09:40.667659

"""
from alembic import op
import sqlalchemy as sa


revision = 'a9edbaef5a0d'
down_revision = 'd14be4f4cf36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cf_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_session_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_session_id')
    op.drop_column('orders', 'cf_order_id')
    # ### end Alembic commands ###
