"""add_product_detail_fields

Revision ID: ccd520744443
Revises: 61392849f386
Create Date: 2026-04-07 01:30:16.294229

"""
from alembic import op
import sqlalchemy as sa


revision = 'ccd520744443'
down_revision = '61392849f386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('specifications', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('use_cases', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('materials', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('delivery_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'delivery_info')
    op.drop_column('products', 'materials')
    op.drop_column('products', 'use_cases')
    op.drop_column('products', 'specifications')
    # ### end Alembic commands ###
