"""add_moq_branding_sizechart

Revision ID: e261ff3092a4
Revises: f8d2c4e6b1a3
Create Date: 2026-04-10 14:04:44.208024

"""
from alembic import op
import sqlalchemy as sa


revision = 'e261ff3092a4'
down_revision = 'f8d2c4e6b1a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_images_variant_id', table_name='product_images')
    op.drop_constraint('fk_product_images_variant', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'product_variants', ['variant_id'], ['id'])
    op.add_column('products', sa.Column('min_order_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('branding_info', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('size_chart_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size_chart_url')
    op.drop_column('products', 'branding_info')
    op.drop_column('products', 'min_order_qty')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('fk_product_images_variant', 'product_images', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_product_images_variant_id', 'product_images', ['variant_id'], unique=False)
    # ### end Alembic commands ###
